// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/grpc/proto/profile.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Profile message based on the YAML contract
type Profile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UserID is typically the Firebase UID and will be used as the document ID in Firestore.
	// It's part of request/response where needed but not stored as a field in the Profile message itself if it's the identifier.
	// However, for returning profile data, it's useful to have.
	UserId        string  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Will be populated from context/path param for requests, and from document ID for responses.
	FullName      string  `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string  `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         *string `protobuf:"bytes,4,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	BirthDate     *string `protobuf:"bytes,5,opt,name=birth_date,json=birthDate,proto3,oneof" json:"birth_date,omitempty"` // ISO 8601 date YYYY-MM-DD
	Cep           *string `protobuf:"bytes,6,opt,name=cep,proto3,oneof" json:"cep,omitempty"`
	City          *string `protobuf:"bytes,7,opt,name=city,proto3,oneof" json:"city,omitempty"`
	State         *string `protobuf:"bytes,8,opt,name=state,proto3,oneof" json:"state,omitempty"` // Timestamps like createdAt, updatedAt can be added if needed, often as google.protobuf.Timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_profile_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Profile) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Profile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Profile) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *Profile) GetBirthDate() string {
	if x != nil && x.BirthDate != nil {
		return *x.BirthDate
	}
	return ""
}

func (x *Profile) GetCep() string {
	if x != nil && x.Cep != nil {
		return *x.Cep
	}
	return ""
}

func (x *Profile) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *Profile) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

// Request to create a profile for the authenticated user.
// UserID will be taken from authenticated context.
type CreateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,3,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	BirthDate     *string                `protobuf:"bytes,4,opt,name=birth_date,json=birthDate,proto3,oneof" json:"birth_date,omitempty"`
	Cep           *string                `protobuf:"bytes,5,opt,name=cep,proto3,oneof" json:"cep,omitempty"`
	City          *string                `protobuf:"bytes,6,opt,name=city,proto3,oneof" json:"city,omitempty"`
	State         *string                `protobuf:"bytes,7,opt,name=state,proto3,oneof" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_profile_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProfileRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateProfileRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *CreateProfileRequest) GetBirthDate() string {
	if x != nil && x.BirthDate != nil {
		return *x.BirthDate
	}
	return ""
}

func (x *CreateProfileRequest) GetCep() string {
	if x != nil && x.Cep != nil {
		return *x.Cep
	}
	return ""
}

func (x *CreateProfileRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *CreateProfileRequest) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

// Response for CreateProfile, returns the created profile.
type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_profile_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// Request to get a profile. UserID is specified in the path.
type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UserID whose profile is being requested
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_profile_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response for GetProfile.
type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_profile_proto_rawDescGZIP(), []int{4}
}

func (x *GetProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// Request to update a profile. UserID is specified in the path.
// Uses optional fields to allow partial updates.
type UpdateProfileRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	UserId   string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UserID whose profile is being updated
	FullName *string                `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3,oneof" json:"full_name,omitempty"`
	// Email is typically not updatable or requires special handling. For now, assume it can be.
	Email         *string `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone         *string `protobuf:"bytes,4,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	BirthDate     *string `protobuf:"bytes,5,opt,name=birth_date,json=birthDate,proto3,oneof" json:"birth_date,omitempty"`
	Cep           *string `protobuf:"bytes,6,opt,name=cep,proto3,oneof" json:"cep,omitempty"`
	City          *string `protobuf:"bytes,7,opt,name=city,proto3,oneof" json:"city,omitempty"`
	State         *string `protobuf:"bytes,8,opt,name=state,proto3,oneof" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_profile_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

func (x *UpdateProfileRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateProfileRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UpdateProfileRequest) GetBirthDate() string {
	if x != nil && x.BirthDate != nil {
		return *x.BirthDate
	}
	return ""
}

func (x *UpdateProfileRequest) GetCep() string {
	if x != nil && x.Cep != nil {
		return *x.Cep
	}
	return ""
}

func (x *UpdateProfileRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *UpdateProfileRequest) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

// Response for UpdateProfile, returns the updated profile.
type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_profile_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// Request to delete a profile. UserID is specified in the path.
type DeleteProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UserID whose profile is being deleted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileRequest) Reset() {
	*x = DeleteProfileRequest{}
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileRequest) ProtoMessage() {}

func (x *DeleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_profile_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response for DeleteProfile (empty).
type DeleteProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileResponse) Reset() {
	*x = DeleteProfileResponse{}
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileResponse) ProtoMessage() {}

func (x *DeleteProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteProfileResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_profile_proto_rawDescGZIP(), []int{8}
}

var File_pkg_grpc_proto_profile_proto protoreflect.FileDescriptor

const file_pkg_grpc_proto_profile_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/grpc/proto/profile.proto\x12\aprofile\"\x93\x02\n" +
	"\aProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x19\n" +
	"\x05phone\x18\x04 \x01(\tH\x00R\x05phone\x88\x01\x01\x12\"\n" +
	"\n" +
	"birth_date\x18\x05 \x01(\tH\x01R\tbirthDate\x88\x01\x01\x12\x15\n" +
	"\x03cep\x18\x06 \x01(\tH\x02R\x03cep\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\a \x01(\tH\x03R\x04city\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\b \x01(\tH\x04R\x05state\x88\x01\x01B\b\n" +
	"\x06_phoneB\r\n" +
	"\v_birth_dateB\x06\n" +
	"\x04_cepB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_state\"\x87\x02\n" +
	"\x14CreateProfileRequest\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x19\n" +
	"\x05phone\x18\x03 \x01(\tH\x00R\x05phone\x88\x01\x01\x12\"\n" +
	"\n" +
	"birth_date\x18\x04 \x01(\tH\x01R\tbirthDate\x88\x01\x01\x12\x15\n" +
	"\x03cep\x18\x05 \x01(\tH\x02R\x03cep\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x06 \x01(\tH\x03R\x04city\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\a \x01(\tH\x04R\x05state\x88\x01\x01B\b\n" +
	"\x06_phoneB\r\n" +
	"\v_birth_dateB\x06\n" +
	"\x04_cepB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_state\"C\n" +
	"\x15CreateProfileResponse\x12*\n" +
	"\aprofile\x18\x01 \x01(\v2\x10.profile.ProfileR\aprofile\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\x12GetProfileResponse\x12*\n" +
	"\aprofile\x18\x01 \x01(\v2\x10.profile.ProfileR\aprofile\"\xc2\x02\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\tfull_name\x18\x02 \x01(\tH\x00R\bfullName\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x01R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x04 \x01(\tH\x02R\x05phone\x88\x01\x01\x12\"\n" +
	"\n" +
	"birth_date\x18\x05 \x01(\tH\x03R\tbirthDate\x88\x01\x01\x12\x15\n" +
	"\x03cep\x18\x06 \x01(\tH\x04R\x03cep\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\a \x01(\tH\x05R\x04city\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\b \x01(\tH\x06R\x05state\x88\x01\x01B\f\n" +
	"\n" +
	"_full_nameB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phoneB\r\n" +
	"\v_birth_dateB\x06\n" +
	"\x04_cepB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_state\"C\n" +
	"\x15UpdateProfileResponse\x12*\n" +
	"\aprofile\x18\x01 \x01(\v2\x10.profile.ProfileR\aprofile\"/\n" +
	"\x14DeleteProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x17\n" +
	"\x15DeleteProfileResponse2\xc7\x02\n" +
	"\x0eProfileService\x12N\n" +
	"\rCreateProfile\x12\x1d.profile.CreateProfileRequest\x1a\x1e.profile.CreateProfileResponse\x12E\n" +
	"\n" +
	"GetProfile\x12\x1a.profile.GetProfileRequest\x1a\x1b.profile.GetProfileResponse\x12N\n" +
	"\rUpdateProfile\x12\x1d.profile.UpdateProfileRequest\x1a\x1e.profile.UpdateProfileResponse\x12N\n" +
	"\rDeleteProfile\x12\x1d.profile.DeleteProfileRequest\x1a\x1e.profile.DeleteProfileResponseB,Z*example.com/profile-service/pkg/grpc/protob\x06proto3"

var (
	file_pkg_grpc_proto_profile_proto_rawDescOnce sync.Once
	file_pkg_grpc_proto_profile_proto_rawDescData []byte
)

func file_pkg_grpc_proto_profile_proto_rawDescGZIP() []byte {
	file_pkg_grpc_proto_profile_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_proto_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_proto_profile_proto_rawDesc), len(file_pkg_grpc_proto_profile_proto_rawDesc)))
	})
	return file_pkg_grpc_proto_profile_proto_rawDescData
}

var file_pkg_grpc_proto_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_grpc_proto_profile_proto_goTypes = []any{
	(*Profile)(nil),               // 0: profile.Profile
	(*CreateProfileRequest)(nil),  // 1: profile.CreateProfileRequest
	(*CreateProfileResponse)(nil), // 2: profile.CreateProfileResponse
	(*GetProfileRequest)(nil),     // 3: profile.GetProfileRequest
	(*GetProfileResponse)(nil),    // 4: profile.GetProfileResponse
	(*UpdateProfileRequest)(nil),  // 5: profile.UpdateProfileRequest
	(*UpdateProfileResponse)(nil), // 6: profile.UpdateProfileResponse
	(*DeleteProfileRequest)(nil),  // 7: profile.DeleteProfileRequest
	(*DeleteProfileResponse)(nil), // 8: profile.DeleteProfileResponse
}
var file_pkg_grpc_proto_profile_proto_depIdxs = []int32{
	0, // 0: profile.CreateProfileResponse.profile:type_name -> profile.Profile
	0, // 1: profile.GetProfileResponse.profile:type_name -> profile.Profile
	0, // 2: profile.UpdateProfileResponse.profile:type_name -> profile.Profile
	1, // 3: profile.ProfileService.CreateProfile:input_type -> profile.CreateProfileRequest
	3, // 4: profile.ProfileService.GetProfile:input_type -> profile.GetProfileRequest
	5, // 5: profile.ProfileService.UpdateProfile:input_type -> profile.UpdateProfileRequest
	7, // 6: profile.ProfileService.DeleteProfile:input_type -> profile.DeleteProfileRequest
	2, // 7: profile.ProfileService.CreateProfile:output_type -> profile.CreateProfileResponse
	4, // 8: profile.ProfileService.GetProfile:output_type -> profile.GetProfileResponse
	6, // 9: profile.ProfileService.UpdateProfile:output_type -> profile.UpdateProfileResponse
	8, // 10: profile.ProfileService.DeleteProfile:output_type -> profile.DeleteProfileResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_grpc_proto_profile_proto_init() }
func file_pkg_grpc_proto_profile_proto_init() {
	if File_pkg_grpc_proto_profile_proto != nil {
		return
	}
	file_pkg_grpc_proto_profile_proto_msgTypes[0].OneofWrappers = []any{}
	file_pkg_grpc_proto_profile_proto_msgTypes[1].OneofWrappers = []any{}
	file_pkg_grpc_proto_profile_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_proto_profile_proto_rawDesc), len(file_pkg_grpc_proto_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_proto_profile_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_proto_profile_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_proto_profile_proto_msgTypes,
	}.Build()
	File_pkg_grpc_proto_profile_proto = out.File
	file_pkg_grpc_proto_profile_proto_goTypes = nil
	file_pkg_grpc_proto_profile_proto_depIdxs = nil
}
