// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/grpc/supportpb/support.proto

package supportpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SupportRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportRequestMessage) Reset() {
	*x = SupportRequestMessage{}
	mi := &file_pkg_grpc_supportpb_support_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportRequestMessage) ProtoMessage() {}

func (x *SupportRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_supportpb_support_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportRequestMessage.ProtoReflect.Descriptor instead.
func (*SupportRequestMessage) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_supportpb_support_proto_rawDescGZIP(), []int{0}
}

func (x *SupportRequestMessage) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SupportRequestMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateSupportRequestRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Request *SupportRequestMessage `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	// Headers like X-APP, X-USERID would typically be passed as metadata in gRPC
	// For this example, we can include them in the request message if needed,
	// or rely on gRPC interceptors to fetch them from metadata.
	// Let's add them to the message for explicitness in this context.
	XApp          string `protobuf:"bytes,2,opt,name=x_app,json=xApp,proto3" json:"x_app,omitempty"`
	XUserid       string `protobuf:"bytes,3,opt,name=x_userid,json=xUserid,proto3" json:"x_userid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSupportRequestRequest) Reset() {
	*x = CreateSupportRequestRequest{}
	mi := &file_pkg_grpc_supportpb_support_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSupportRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSupportRequestRequest) ProtoMessage() {}

func (x *CreateSupportRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_supportpb_support_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSupportRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateSupportRequestRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_supportpb_support_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSupportRequestRequest) GetRequest() *SupportRequestMessage {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CreateSupportRequestRequest) GetXApp() string {
	if x != nil {
		return x.XApp
	}
	return ""
}

func (x *CreateSupportRequestRequest) GetXUserid() string {
	if x != nil {
		return x.XUserid
	}
	return ""
}

type CreateSupportRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusMessage string                 `protobuf:"bytes,1,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Example: could be an ID from Firestore
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSupportRequestResponse) Reset() {
	*x = CreateSupportRequestResponse{}
	mi := &file_pkg_grpc_supportpb_support_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSupportRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSupportRequestResponse) ProtoMessage() {}

func (x *CreateSupportRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_supportpb_support_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSupportRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateSupportRequestResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_supportpb_support_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSupportRequestResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *CreateSupportRequestResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_pkg_grpc_supportpb_support_proto protoreflect.FileDescriptor

const file_pkg_grpc_supportpb_support_proto_rawDesc = "" +
	"\n" +
	" pkg/grpc/supportpb/support.proto\x12\tsupportpb\"U\n" +
	"\x15SupportRequestMessage\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x89\x01\n" +
	"\x1bCreateSupportRequestRequest\x12:\n" +
	"\arequest\x18\x01 \x01(\v2 .supportpb.SupportRequestMessageR\arequest\x12\x13\n" +
	"\x05x_app\x18\x02 \x01(\tR\x04xApp\x12\x19\n" +
	"\bx_userid\x18\x03 \x01(\tR\axUserid\"d\n" +
	"\x1cCreateSupportRequestResponse\x12%\n" +
	"\x0estatus_message\x18\x01 \x01(\tR\rstatusMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId2y\n" +
	"\x0eSupportService\x12g\n" +
	"\x14CreateSupportRequest\x12&.supportpb.CreateSupportRequestRequest\x1a'.supportpb.CreateSupportRequestResponseB3Z1github.com/user/supportservice/pkg/grpc/supportpbb\x06proto3"

var (
	file_pkg_grpc_supportpb_support_proto_rawDescOnce sync.Once
	file_pkg_grpc_supportpb_support_proto_rawDescData []byte
)

func file_pkg_grpc_supportpb_support_proto_rawDescGZIP() []byte {
	file_pkg_grpc_supportpb_support_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_supportpb_support_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_supportpb_support_proto_rawDesc), len(file_pkg_grpc_supportpb_support_proto_rawDesc)))
	})
	return file_pkg_grpc_supportpb_support_proto_rawDescData
}

var file_pkg_grpc_supportpb_support_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_grpc_supportpb_support_proto_goTypes = []any{
	(*SupportRequestMessage)(nil),        // 0: supportpb.SupportRequestMessage
	(*CreateSupportRequestRequest)(nil),  // 1: supportpb.CreateSupportRequestRequest
	(*CreateSupportRequestResponse)(nil), // 2: supportpb.CreateSupportRequestResponse
}
var file_pkg_grpc_supportpb_support_proto_depIdxs = []int32{
	0, // 0: supportpb.CreateSupportRequestRequest.request:type_name -> supportpb.SupportRequestMessage
	1, // 1: supportpb.SupportService.CreateSupportRequest:input_type -> supportpb.CreateSupportRequestRequest
	2, // 2: supportpb.SupportService.CreateSupportRequest:output_type -> supportpb.CreateSupportRequestResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_grpc_supportpb_support_proto_init() }
func file_pkg_grpc_supportpb_support_proto_init() {
	if File_pkg_grpc_supportpb_support_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_supportpb_support_proto_rawDesc), len(file_pkg_grpc_supportpb_support_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_supportpb_support_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_supportpb_support_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_supportpb_support_proto_msgTypes,
	}.Build()
	File_pkg_grpc_supportpb_support_proto = out.File
	file_pkg_grpc_supportpb_support_proto_goTypes = nil
	file_pkg_grpc_supportpb_support_proto_depIdxs = nil
}
